// Package utils 提供通用工具函数
package utils

import "strings"

// IsBot 检查 User-Agent 是否为爬虫
func IsBot(userAgent string) bool {
	// 使用 map 存储爬虫特征，提高查找效率
	// 空结构体仅占用 0 字节空间
	static := struct{}{}
	botSignatures := map[string]struct{}{
		"bot":                   static,
		"spider":                static,
		"crawler":               static,
		"googlebot":             static,
		"baiduspider":           static,
		"bytespider":            static,
		"yandex":                static,
		"bingbot":               static,
		"slurp":                 static,
		"duckduckbot":           static,
		"semrushbot":            static,
		"ahrefsbot":             static,
		"mj12bot":               static,
		"sogou":                 static,
		"petalbot":              static,
		"exabot":                static,
		"facebookexternalhit":   static,
		"ia_archiver":           static,
		"robot":                 static,
		"scanner":                static,
		"python-requests":       static,
		"java/":                 static,
		"curl/":                 static,
		"wget/":                 static,
		"nutch":                 static,
		"httrack":               static,
		"archive.org":           static,
		"metauri":               static,
		"ltx71":                 static,
		"qwantify":              static,
		"panscient":              static,
		"yacybot":               static,
		"sistrix":               static,
		"dotbot":                static,
		"megaindex":             static,
		"blexbot":               static,
		"rogerbot":               static,
		"linkdexbot":             static,
		"seokicks":               static,
		"seoscanners":            static,
		"serpstatbot":            static,
		"sitechecker":            static,
		"seostar":                static,
		"seobility":              static,
		"zgrab":                  static,
		"zoominfobot":            static,
		"proximic":               static,
		"netcraft":               static,
		"cloudflare":             static,
		"uptimebot":              static,
		"pingdom":                static,
		"newrelic":               static,
		"monitor":                static,
		"statuscake":             static,
		"datadog":                static,
		"appdynamics":            static,
		"headlesschrome":         static,
		"phantomjs":             static,
		"selenium":               static,
		"webdriver":              static,
		"lighthouse":             static,
		"apifox":                 static,
		"postman":                static,
		"insomnia/":              static,
		"go-http-client":         static,
		"okhttp/":                static,
		"node-fetch":             static,
		"axios/":                 static,
		"ruby":                   static,
		"python-urllib":          static,
		"libwww-perl":            static,
		"winhttp":                static,
		"microsoft url control":   static,
		"msie ":                  static,
		"internet explorer":      static,
		"yisouspider":            static,
		"360spider":              static,
		"haosouspider":           static,
		"dnspod":                 static,
		"ccbot":                  static,
		"admantx":                static,
		"grapeshot":              static,
		"alexa":                  static,
		"similarweb":             static,
		"moatbot":                static,
		"mediabot":               static,
		"weborama":               static,
		"adbeat":                 static,
		"brandwatch":             static,
		"screaming frog":         static,
		"hubspot":                static,
		"mail.ru":                static,
		"aolbuild":               static,
		"teoma":                  static,
		"ask jeeves":             static,
		"lycos":                  static,
		"infoseek":               static,
		"webcrawler":             static,
		"gigabot":                static,
		"genieo":                 static,
		"surdotly":               static,
		"nerdybot":               static,
		"barkrowler":             static,
		"meanpathbot":            static,
		"heritrix":               static,
		"netresearchserver":      static,
		"xenu":                   static,
		"linkwalker":             static,
		"purebot":                static,
		"voyager":                static,
		"extract":                static,
		"checkmarknetwork":       static,
		"dnyzbot":                static,
		"discordbot":             static,
		"twitterbot":             static,
		"telegrambot":            static,
		"whatsapp":               static,
		"slackbot":               static,
		"kakaotalk":              static,
		"linebot":                static,
		"viber":                  static,
		"skypeuripreview":        static,
		"linkedinbot":            static,
		"embedly":                static,
		"quora bot":              static,
		"redditbot":              static,
		"iframely":               static,
		"pinterest":              static,
		"flipboard":              static,
		"tumblr":                 static,
		"wordpress":              static,
		"jooble":                 static,
		"jobboerse":              static,
		"careerbot":              static,
		"najdi.si":               static,
		"searchmetrics":          static,
		"trendiction":            static,
		"ezooms":                 static,
		"domainappender":         static,
		"magpie-crawler":         static,
		"omgili":                 static,
		"smtbot":                 static,
		"mauibot":                static,
		"paperlibot":             static,
		"drupact":                static,
		"jikeSpider":             static,
		"yodaobot":               static,
	}

	userAgent = strings.ToLower(userAgent)

	// 使用 map 查找比遍历数组更高效
	for sig := range botSignatures {
		if strings.Contains(userAgent, sig) {
			return true
		}
	}

	return false
}

